
#logging
logging:
  level:
    org.springframework.data: debug
    .: error

# Mongo db

#mongodb
spring:
  data:
    mongodb:
      uri: mongodb://elewandowski:Fpzqyqvh1$@elewandowski-shard-00-01-fhyul.mongodb.net:27017,elewandowski-shard-00-00-fhyul.mongodb.net:27017,elewandowski-shard-00-02-fhyul.mongodb.net:27017/nf?ssl=true&replicaSet=elewandowski-shard-0&authSource=admin


#security
#spring security with OAUTH2 and JWT
security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: UHZ6qiPhFcvjle7qmzcMdfSxpOcM7kFQ
  encoding-strength: 256
  security-realm: NF Realm
  jwt:
    client-id: nfbatch
    client-secret: nfbatchpassword
    scope-read: perso.read
    scope-write: perso.write
    resource-ids: http://NF.backend

genetic:
    humangenomeref:
      - H-BB; Couleur de cheveux - Brun ou blond; 1=noir, 2=brun, 3=châtain foncé, 4=châtain, 5=châtain clair, 6=blond foncé, 7=blond moyen, 8=blond clair, 9=blond très clair, 10=blond platine ; HY;1;4
      - H-R; Couleur de cheveux - Roux; 1 = roux (dominant), 0 = pas de rousseur; HY;5;5



