#server.port=8081

#Web environnement for Spring boot
spring:
  main:
    webEnvironment: false

com:
  es:
    nf:
      ws:
        #OAUTH2 configuration
        oauth2:
          domain: elewandowski.auth0.com
          tokenUrl: https://elewandowski.auth0.com/oauth/token
          portAccessTokenUrl: 443
          clientId: LdoMb0hez4nVj98Vbji9rqVs7wgZFb26
          clientSecret: ${AUTH0_PWD}
          audience: http://NF.backend
          #Services configuration
      genator:
        services:
          url:
            bfBase: https://nfapi.herokuapp.com/v1/biologicalfiles
            bfListColon: https://nfapi.herokuapp.com/v1/biologicalfiles/parents/0
            persoBase: https://nfapi.herokuapp.com/v1/personnages
